print(deda "37")
print(mama "38")
print(bebia "66")
print(da "15")
print (bidza "40")
print(deida"40")
print(babua "61")
print(bidzashvili "16")
print(me "14")
print("zestafonis qucha")
print(sadarbazo "1")
print(bina "16")
print(sartuli "1")